databases:
  - name: Todo_application
    databaseName: Todo_application
    user: Todo_application
    plan: free

services:
  - type: web
    plan: free
    name: Todo_application
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Todo_application
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false